version: "3.7"

services:
  rabbitmq:
    container_name: nest_microservices_rabbitmq
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    volumes:
      - ./.docker/rabbitmq/:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./rabbitmq.env

networks:
  nestjs_microservices:
    driver: bridge
